server:
  port: 8081

spring:
  jpa:
    database: mysql
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery?createDatabaseIfNotExists=true
    username: root
    password: root
  sql:
    init:
      platform: org.hibernate.dialect.MySQL5Dialect